#!/usr/bin/env ansible-playbook
---
- name: Undercloud part of gnocchi testing
  hosts: localhost
  tasks:
      - name: Clone git repo to undercloud
        git:
          repo: "https://github.com/sashkavyshka/gnocchi_auto.git"
          dest: "~/gnocchi_auto"

      - name: Change permissions
        file:
          path: gnocchi_auto
          mode: 0770

      - name: Run python tests on overcloud
        shell: |
          source ~/overcloudrc.v3;
          sudo python gnocchi_auto/RHELOSP_6835_pretest.py;
          sudo python gnocchi_auto/RHELOSP_6841_pretest.py;
          sudo python gnocchi_auto/RHELOSP_6842_pretest.py;
          sudo python gnocchi_auto/RHELOSP_6844_pretest.py;
          sudo python gnocchi_auto/RHELOSP_7043_pretest.py;
          sudo python gnocchi_auto/RHELOSP_7044_pretest.py;
          sudo chmod 770 /etc/ceilometer/pipeline.yaml;
          sudo chown ceilometer /etc/ceilometer/pipeline.yaml;
          sudo chmod 770 /etc/ceilometer/gnocchi_resources.yaml;
          sudo chown ceilometer /etc/ceilometer/gnocchi_resources.yaml;
          python gnocchi_auto/RHELOSP_6835.py;
          python gnocchi_auto/RHELOSP_6841.py;
          python gnocchi_auto/RHELOSP_6842.py;
          python gnocchi_auto/RHELOSP_6844.py;
          python gnocchi_auto/RHELOSP_7043.py;
          python gnocchi_auto/RHELOSP_7044.py;

