#!/usr/bin/env ansible-playbook
---
- name: Undercloud part of gnocchi testing
  hosts: undercloud-0
  tasks:
      - name: Clone git repo to undercloud
        git:
          repo: "https://github.com/sashkavyshka/gnocchi_auto.git"
          dest: "~/gnocchi_auto"

      - name: Copy overcloudrc to controller
        shell: |
          source ~/stackrc;
          ssh-keyscan $(openstack server list -f value | grep controller-0 | cut -d " " -f 4 | cut -d "=" -f 2) >  ~/.ssh/known_hosts;
          scp {overcloudrc_file} heat-admin@$(openstack server list -f value | grep controller-0 | cut -d " " -f 4 | cut -d "=" -f 2):stackrc

- name: Tests on controller
  hosts: controller-0
  tasks:
      - name: Clone git repo to controller
        git:
          repo: "https://github.com/sashkavyshka/gnocchi_auto.git"
          dest: "~/gnocchi_auto"

      - name: Change permissions
        file:
          path: gnocchi_auto
          mode: 0770

      - name: Run python tests on overcloud
        shell: |
          source ~/stackrc;
          python gnocchi_auto/RHELOSP_6835.py;
          python gnocchi_auto/RHELOSP_6841.py;
          python gnocchi_auto/RHELOSP_6842.py;
          python gnocchi_auto/RHELOSP_6844.py;
          python gnocchi_auto/RHELOSP_7043.py;
          python gnocchi_auto/RHELOSP_7044.py;

      - name: Run neutron tests on overcloud
        shell: |
          python gnocchi_auto/RHELOSP_6843.py;
        when: product_version == "10"